GET http://localhost:4649/cart/


###
POST http://localhost:4649/cart/623d95c6b7d8e4fe5cd181fe
Content-Type: application/json

{
                    "products": [
                      {
                        "productId": "623459afaf6564d90225f904",
                         "qty": 1
                      }
                    ]
                  
}

###
DELETE  http://localhost:4649/cart/

###
PATCH http://localhost:4649/cart/623b0a6f060f0b8bfa71de0c
Content-Type: application/json

{
   
}